### ISSUE TITLE
Invalid password

### ISSUE THREAD

**Issue by xeo545x39** [denis-ivanov/EntityFrameworkCore.ClickHouse#78]
Hi,

I use 1.0.1 version of the package and when trying to connect from code I receive the following error. When I try to connect with same credentials from JetBrains Rider it connects **successully**.

![Image](https://github.com/user-attachments/assets/12cad216-c6e1-4fcb-990a-6e6e2fbae631)

Connection string:
`Host=localhost;Protocol=http;Port=8123;Integrated Security=false;Database=historical;User ID=admin;Password=admin`

```bash
fail: Microsoft.EntityFrameworkCore.Query[10100]
      An exception occurred while iterating over the results of a query for context type 'Application.Data.HistoricalDbContext'.
      ClickHouse.Client.ClickHouseServerException (0x000000C2): Code: 194. DB::Exception: default: Authentication failed: password is incorrect, or there is no user with such name.

If you use ClickHouse Cloud, the password can be reset at https://clickhouse.cloud/
on the settings page for the corresponding service.

If you have installed ClickHouse and forgot password you can reset it in the configuration file.
The password for default user is typically located at /etc/clickhouse-server/users.d/default-password.xml
and deleting this file will reset the password.
See also /etc/clickhouse-server/users.xml on the server where ClickHouse is installed.

. (REQUIRED_PASSWORD) (version 25.3.1.2703 (official build))

         at ClickHouse.Client.ADO.ClickHouseConnection.HandleError(HttpResponseMessage response, String query, Activity activity)
         at ClickHouse.Client.ADO.ClickHouseConnection.OpenAsync(CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternalAsync(Boolean errorsExpected, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternalAsync(Boolean errorsExpected, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
         at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
      ClickHouse.Client.ClickHouseServerException (0x000000C2): Code: 194. DB::Exception: default: Authentication failed: password is incorrect, or there is no user with such name.

If you use ClickHouse Cloud, the password can be reset at https://clickhouse.cloud/
on the settings page for the corresponding service.

If you have installed ClickHouse and forgot password you can reset it in the configuration file.
The password for default user is typically located at /etc/clickhouse-server/users.d/default-password.xml
and deleting this file will reset the password.
See also /etc/clickhouse-server/users.xml on the server where ClickHouse is installed.

```

The code:
```csharp
builder.Services.AddDbContextFactory<HistoricalDbContext>((services, optionsBuilder) => optionsBuilder.UseClickHouse(
    services.GetRequiredService<ClickHouseOptions>()
        .ConnectionString));
```

Checked `Database` EF property - connection string looks good as in config.

Tried without integrated secutity = the same.

I use ClickHouse on Docker - [Docker Image](https://hub.docker.com/layers/library/clickhouse/latest/images/sha256-8c6978ba7c96a19335334b4c320aa0c99ab4ca15bb27c2455181cec18755b190)

Container output:

![Image](https://github.com/user-attachments/assets/93b50755-6bc3-4e75-96af-489c9671aa33)

Compose:

```yaml
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    restart: always
    ports:
      - "8123:8123"   # HTTP interface
      - "9000:9000"   # Native client interface
      - "9009:9009"   # Interserver communication
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - clickhouse_logs:/var/log/clickhouse-server
    environment:
      CLICKHOUSE_USER: admin
      CLICKHOUSE_PASSWORD: admin
      CLICKHOUSE_DB: historical
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
```
